name: Test and Test Coverage

on:
    workflow_dispatch:
    pull_request:
        branches:
            - develop
            - main

jobs:
    typecheck-and-test:
        name: typecheck-and-test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node 20
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Type-check client
              run: npx tsc -p client/tsconfig.json --noEmit

            - name: Type-check server
              run: npx tsc -p server/tsconfig.json --noEmit

            - name: Test client
              run: npm run test:coverage -w client

            - name: Test server
              run: npm run test:coverage -w server
